-- Arquivo historico preservado para evitar que instrucoes antigas quebrem.
-- Nao execute SQL manual deste diretorio.
-- A tabela analytics_events, os indices, privilegios e RLS agora fazem parte de:
-- supabase/migrations/20260805000000_initial_pianify_schema.sql
